[build]
  functions = "netlify/functions"
  command = "npm run build" # Your build command here
  publish = "public" # Your static files directory

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/express-server"
  status = 200
